#FROM protocol:1.0.1
#MAINTAINER "Jacky123"

#WORKDIR /usr/wic-go
#RUN go env -w GO111MODULE=on
#RUN go env -w GOPROXY=https://proxy.golang.org,direct
#ADD . /usr/wic-go
#COPY ./conf/app-http.conf /usr/wic-go/conf/app.conf
#RUN go mod download
#RUN go build main.go

#RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
# 构建阶段

#EXPOSE 8005
#ENTRYPOINT ["./main"]


# 使用 Alpine 作为基础镜像
FROM ubuntu:latest





# 将当前目录的 main 文件复制到容器的 /app 目录下
COPY . .

# 暴露容器的 8005 端口
EXPOSE 8005

# 设置容器启动时运行的命令
CMD ["./main"]