#FROM protocol:1.0.1
#MAINTAINER "Jacky123"

#WORKDIR /usr/wic-go
#RUN go env -w GO111MODULE=on
#RUN go env -w GOPROXY=https://proxy.golang.org,direct
#ADD . /usr/wic-go
#COPY ./conf/app-http.conf /usr/wic-go/conf/app.conf
#RUN go mod download
#RUN go build main.go

#RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
# 构建阶段

#EXPOSE 8005
#ENTRYPOINT ["./main"]


FROM ubuntu:latest


# 创建一个工作目录
RUN mkdir -p /app

# 将当前目录下的所有文件复制到 /app 目录
COPY . /app/

# 设置工作目录
WORKDIR /app

# 暴露端口
EXPOSE 8057

# 设置容器启动时运行的命令
CMD ["./main"]