appname = wechatwebapi
httpaddr = ""
httpport = 8005
runmode = prod
viewspath = "template"
autorender = false
copyrequestbody = true
EnableDocs = true
redislink = 8.141.174.247:6379
redispass = "redis_w4HJTm"
redisdbnum = 1
ocrurl = "http://150.158.2.208:9008/api/UnBan/WXSliderOCR"
syncmessagebusinessuri = "http://150.158.2.208:9100/wic/wechat/{0}/SyncMessage"
logoutbusinessuri = "http://150.158.2.208:9100/wic/wechat/{0}/logoutSys"

sessionon = true

SessionName = "wicgo"
ServerName = "wicgo"

longlinkenabled = false
longlinkconnecttimeout = "1m"

