appname = wxapi
httpaddr = "0.0.0.0"
httpport = 8057
runmode = prod
viewspath = "template"
autorender = false
copyrequestbody = true
EnableDocs = true
redislink = redis:6379
redispass = "CHANGE_ME_REDIS_PASSWORD"
redisdbnum = 7
ocrurl = ""
syncmessagebusinessuri = ""
logoutbusinessuri = ""

sessionon = true

SessionName = "wxapi"
ServerName = "wxapi"

longlinkenabled = true
longlinkconnecttimeout = "1m"

