appname = wxapi
httpaddr = "0.0.0.0"
httpport = 8057
runmode = dev
viewspath = "template"
autorender = false
copyrequestbody = true
EnableDocs = true
redislink = 8.141.174.247:6379
redispass = "redis_w4HJTm"
redisdbnum = 7
ocrurl = ""
syncmessagebusinessuri = ""
logoutbusinessuri = ""

sessionon = true

SessionName = "wxapi"
ServerName = "wxapi"

longlinkenabled = true
longlinkconnecttimeout = "1m"

